services:
  - type: web
    name: shift-tool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PERSISTENT_STORAGE_PATH
        value: /var/data
    disk:
      name: shift-data
      mountPath: /var/data
      sizeGB: 1
